"""
五套精选配色方案（均可在设置中切换）。
"""

from __future__ import annotations

from typing import Dict, List

# 每套含：展示名 + 完整 style 字典
THEMES: Dict[str, dict] = {
    "midnight": {
        "name": "午夜玻璃",
        "desc": "默认 · 深黑 + 青紫绿",
        "style": {
            "accent_cpu": "#64D2FF",
            "accent_mem": "#BF5AF2",
            "accent_gpu": "#32D74B",
            "accent_up": "#FF9F0A",
            "accent_down": "#0A84FF",
            "text_primary": "#F5F5F7",
            "text_secondary": "#8E8E93",
            "text_tertiary": "#636366",
            "glass_bg": "#121214",
            "glass_card": "#1C1C1E",
            "glass_elevated": "#2C2C2E",
            "glass_border": "#3A3A3C",
            "separator": "#2C2C2E",
            "traffic_green": "#32D74B",
            "traffic_yellow": "#FFD60A",
            "traffic_red": "#FF453A",
        },
    },
    "ocean": {
        "name": "深海静谧",
        "desc": "靛蓝底 + 海蓝强调",
        "style": {
            "accent_cpu": "#5AC8FA",
            "accent_mem": "#66D4CF",
            "accent_gpu": "#0A84FF",
            "accent_up": "#64D2FF",
            "accent_down": "#007AFF",
            "text_primary": "#E8F4FF",
            "text_secondary": "#8EADC7",
            "text_tertiary": "#5A7A94",
            "glass_bg": "#0B1220",
            "glass_card": "#121C2E",
            "glass_elevated": "#1A2A42",
            "glass_border": "#2A3F5C",
            "separator": "#1A2A42",
            "traffic_green": "#30D158",
            "traffic_yellow": "#FFD60A",
            "traffic_red": "#FF453A",
        },
    },
    "sakura": {
        "name": "樱夜粉紫",
        "desc": "暗紫底 + 樱粉点缀",
        "style": {
            "accent_cpu": "#C084FC",
            "accent_mem": "#B8A1FF",
            "accent_gpu": "#BF5AF2",
            "accent_up": "#FF6B8A",
            "accent_down": "#DA8FFF",
            "text_primary": "#FFF0F5",
            "text_secondary": "#C9A0B0",
            "text_tertiary": "#8A6A78",
            "glass_bg": "#160E14",
            "glass_card": "#22151E",
            "glass_elevated": "#33202C",
            "glass_border": "#4A3040",
            "separator": "#33202C",
            "traffic_green": "#30D158",
            "traffic_yellow": "#FFD60A",
            "traffic_red": "#FF453A",
        },
    },
    "forest": {
        "name": "森野暖焰",
        "desc": "墨绿底 + 叶绿 / 琥珀",
        "style": {
            "accent_cpu": "#30D158",
            "accent_mem": "#A8DAB5",
            "accent_gpu": "#7ED6C3",
            "accent_up": "#FFB340",
            "accent_down": "#34C759",
            "text_primary": "#F0F5F0",
            "text_secondary": "#9BB09B",
            "text_tertiary": "#6A7A6A",
            "glass_bg": "#0E1410",
            "glass_card": "#161E18",
            "glass_elevated": "#243028",
            "glass_border": "#354538",
            "separator": "#243028",
            "traffic_green": "#30D158",
            "traffic_yellow": "#FFD60A",
            "traffic_red": "#FF453A",
        },
    },
    "mono": {
        "name": "银灰极简",
        "desc": "中性灰阶 · 克制高级",
        "style": {
            "accent_cpu": "#E5E5EA",
            "accent_mem": "#AEAEB2",
            "accent_gpu": "#8E8E93",
            "accent_up": "#D1D1D6",
            "accent_down": "#636366",
            "text_primary": "#F2F2F7",
            "text_secondary": "#AEAEB2",
            "text_tertiary": "#636366",
            "glass_bg": "#1C1C1E",
            "glass_card": "#2C2C2E",
            "glass_elevated": "#3A3A3C",
            "glass_border": "#48484A",
            "separator": "#3A3A3C",
            "traffic_green": "#8E8E93",
            "traffic_yellow": "#AEAEB2",
            "traffic_red": "#E5E5EA",
        },
    },
    "aurora": {
        "name": "极光薄荷",
        "desc": "深青玻璃 + 薄荷 / 紫罗兰",
        "style": {
            "accent_cpu": "#5DE2C2",
            "accent_mem": "#B39DFF",
            "accent_gpu": "#76B7FF",
            "accent_up": "#65E6C2",
            "accent_down": "#8D9BFF",
            "text_primary": "#ECFFFA",
            "text_secondary": "#91BDB7",
            "text_tertiary": "#5D817D",
            "glass_bg": "#0A1718",
            "glass_card": "#102425",
            "glass_elevated": "#1B3838",
            "glass_border": "#2B5551",
            "separator": "#1B3838",
            "traffic_green": "#30D158",
            "traffic_yellow": "#FFD60A",
            "traffic_red": "#FF453A",
        },
    },
    "cobalt": {
        "name": "钴蓝暮光",
        "desc": "深蓝玻璃 + 冰蓝 / 靛紫",
        "style": {
            "accent_cpu": "#72D7FF",
            "accent_mem": "#9F9CFF",
            "accent_gpu": "#62E6C9",
            "accent_up": "#79C8FF",
            "accent_down": "#8EAEFF",
            "text_primary": "#F0F5FF",
            "text_secondary": "#9AAAC8",
            "text_tertiary": "#627493",
            "glass_bg": "#0A1020",
            "glass_card": "#111B32",
            "glass_elevated": "#1D2C4A",
            "glass_border": "#30476D",
            "separator": "#1D2C4A",
            "traffic_green": "#30D158",
            "traffic_yellow": "#FFD60A",
            "traffic_red": "#FF453A",
        },
    },
    "lavender": {
        "name": "薰衣草夜",
        "desc": "蓝紫玻璃 + 紫晶 / 冰蓝",
        "style": {
            "accent_cpu": "#A78BFA",
            "accent_mem": "#C4B5FD",
            "accent_gpu": "#7DD3FC",
            "accent_up": "#B8A1FF",
            "accent_down": "#93C5FD",
            "text_primary": "#FAF7FF",
            "text_secondary": "#B8AFCB",
            "text_tertiary": "#766B8D",
            "glass_bg": "#130F1F",
            "glass_card": "#1E1730",
            "glass_elevated": "#30234A",
            "glass_border": "#4D3970",
            "separator": "#30234A",
            "traffic_green": "#30D158",
            "traffic_yellow": "#FFD60A",
            "traffic_red": "#FF453A",
        },
    },
    "frost": {
        "name": "冰川雾白",
        "desc": "冷灰玻璃 + 冰蓝 / 青绿",
        "style": {
            "accent_cpu": "#5AC8FA",
            "accent_mem": "#AF9FFF",
            "accent_gpu": "#63D8C5",
            "accent_up": "#72D7EE",
            "accent_down": "#8AA9FF",
            "text_primary": "#F4FBFF",
            "text_secondary": "#A4BBC7",
            "text_tertiary": "#718A98",
            "glass_bg": "#11171B",
            "glass_card": "#1C252B",
            "glass_elevated": "#2A3942",
            "glass_border": "#405560",
            "separator": "#2A3942",
            "traffic_green": "#30D158",
            "traffic_yellow": "#FFD60A",
            "traffic_red": "#FF453A",
        },
    },
    "deep_space": {
        "name": "深空星云",
        "desc": "墨蓝玻璃 + 星紫 / 青蓝",
        "style": {
            "accent_cpu": "#7DD3FC",
            "accent_mem": "#A78BFA",
            "accent_gpu": "#5EEAD4",
            "accent_up": "#67E8F9",
            "accent_down": "#818CF8",
            "text_primary": "#F1F5FF",
            "text_secondary": "#9CA9C7",
            "text_tertiary": "#626F8C",
            "glass_bg": "#090D1A",
            "glass_card": "#11182A",
            "glass_elevated": "#1D2942",
            "glass_border": "#304267",
            "separator": "#1D2942",
            "traffic_green": "#30D158",
            "traffic_yellow": "#FFD60A",
            "traffic_red": "#FF453A",
        },
    },
    "teal_noir": {
        "name": "青黛 noir",
        "desc": "青黛玻璃 + 薄荷 / 靛蓝",
        "style": {
            "accent_cpu": "#2DD4BF",
            "accent_mem": "#818CF8",
            "accent_gpu": "#A5B4FC",
            "accent_up": "#5EEAD4",
            "accent_down": "#60A5FA",
            "text_primary": "#EDFFFC",
            "text_secondary": "#91B5B2",
            "text_tertiary": "#5F817F",
            "glass_bg": "#091516",
            "glass_card": "#102122",
            "glass_elevated": "#1B3636",
            "glass_border": "#2C5553",
            "separator": "#1B3636",
            "traffic_green": "#30D158",
            "traffic_yellow": "#FFD60A",
            "traffic_red": "#FF453A",
        },
    },
    "plum": {
        "name": "梅子暮紫",
        "desc": "深梅玻璃 + 冷紫 / 雾蓝",
        "style": {
            "accent_cpu": "#C4B5FD",
            "accent_mem": "#A5B4FC",
            "accent_gpu": "#67E8F9",
            "accent_up": "#D8B4FE",
            "accent_down": "#93C5FD",
            "text_primary": "#FCF7FF",
            "text_secondary": "#B9A9C9",
            "text_tertiary": "#796A88",
            "glass_bg": "#170F20",
            "glass_card": "#251631",
            "glass_elevated": "#39234A",
            "glass_border": "#5A3970",
            "separator": "#39234A",
            "traffic_green": "#30D158",
            "traffic_yellow": "#FFD60A",
            "traffic_red": "#FF453A",
        },
    },
    "mint_graphite": {
        "name": "石墨薄荷",
        "desc": "石墨玻璃 + 薄荷 / 冰紫",
        "style": {
            "accent_cpu": "#6EE7B7",
            "accent_mem": "#A5B4FC",
            "accent_gpu": "#93C5FD",
            "accent_up": "#86EFAC",
            "accent_down": "#7DD3FC",
            "text_primary": "#F2FFFA",
            "text_secondary": "#A1B8B1",
            "text_tertiary": "#6B807A",
            "glass_bg": "#111617",
            "glass_card": "#1B2324",
            "glass_elevated": "#2A3535",
            "glass_border": "#40504F",
            "separator": "#2A3535",
            "traffic_green": "#30D158",
            "traffic_yellow": "#FFD60A",
            "traffic_red": "#FF453A",
        },
    },
    "arctic": {
        "name": "北境极光",
        "desc": "深灰蓝玻璃 + 极光青 / 冰紫",
        "style": {
            "accent_cpu": "#67E8F9",
            "accent_mem": "#C4B5FD",
            "accent_gpu": "#86EFAC",
            "accent_up": "#7DD3FC",
            "accent_down": "#A5B4FC",
            "text_primary": "#F2FCFF",
            "text_secondary": "#A5BAC5",
            "text_tertiary": "#708791",
            "glass_bg": "#0D151A",
            "glass_card": "#172329",
            "glass_elevated": "#263740",
            "glass_border": "#3B5661",
            "separator": "#263740",
            "traffic_green": "#30D158",
            "traffic_yellow": "#FFD60A",
            "traffic_red": "#FF453A",
        },
    },
    "blueprint": {
        "name": "蓝图夜航",
        "desc": "藏蓝玻璃 + 钴蓝 / 青紫",
        "style": {
            "accent_cpu": "#60A5FA",
            "accent_mem": "#818CF8",
            "accent_gpu": "#22D3EE",
            "accent_up": "#38BDF8",
            "accent_down": "#A5B4FC",
            "text_primary": "#EFF6FF",
            "text_secondary": "#9BAEC7",
            "text_tertiary": "#637794",
            "glass_bg": "#0A1221",
            "glass_card": "#111D32",
            "glass_elevated": "#1D3050",
            "glass_border": "#31527D",
            "separator": "#1D3050",
            "traffic_green": "#30D158",
            "traffic_yellow": "#FFD60A",
            "traffic_red": "#FF453A",
        },
    },
}

THEME_ORDER: List[str] = [
    "midnight", "ocean", "sakura", "forest", "mono",
    "aurora", "cobalt", "lavender", "frost", "deep_space",
    "teal_noir", "plum", "mint_graphite", "arctic", "blueprint",
]


def get_theme(theme_id: str) -> dict:
    return THEMES.get(theme_id) or THEMES["midnight"]


def style_for(theme_id: str) -> dict:
    return dict(get_theme(theme_id)["style"])


def theme_choices() -> List[tuple]:
    """[(id, '显示名 — 描述'), ...]"""
    out = []
    for tid in THEME_ORDER:
        t = THEMES[tid]
        out.append((tid, f"{t['name']}  ·  {t['desc']}"))
    return out
